title: "Vielfalter-KL e.V."
author: ""
description: "Vielfalter-KL e.V."
permalink: /:title/
lang: "de"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Home"}
  - {file: "articles.html", title: News"}
  - {file: "about.html", title: "Über uns"}
  - {file: "contact.html", title: "Kontakt"}
  

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:vielfalter-kl@gmail.com"}
  - {title: Facebook, icon: facebook, url: "https://facebook.com/vielfalterkl"}
  # - {title: Github, icon: github, url: "https://github.com/niklasbuschmann/contrast"}
  # - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
